import { Schema as S } from "effect";

// Enums
const AdActiveStatus = S.Literal("ACTIVE", "ALL", "INACTIVE");

const Country = S.Literal(
	"ALL",
	"BR",
	"IN",
	"GB",
	"US",
	"CA",
	"AR",
	"AU",
	"AT",
	"BE",
	"CL",
	"CN",
	"CO",
	"HR",
	"DK",
	"DO",
	"EG",
	"FI",
	"FR",
	"DE",
	"GR",
	"HK",
	"ID",
	"IE",
	"IL",
	"IT",
	"JP",
	"JO",
	"KW",
	"LB",
	"MY",
	"MX",
	"NL",
	"NZ",
	"NG",
	"NO",
	"PK",
	"PA",
	"PE",
	"PH",
	"PL",
	"RU",
	"SA",
	"RS",
	"SG",
	"ZA",
	"KR",
	"ES",
	"SE",
	"CH",
	"TW",
	"TH",
	"TR",
	"AE",
	"VE",
	"PT",
	"LU",
	"BG",
	"CZ",
	"SI",
	"IS",
	"SK",
	"LT",
	"TT",
	"BD",
	"LK",
	"KE",
	"HU",
	"MA",
	"CY",
	"JM",
	"EC",
	"RO",
	"BO",
	"GT",
	"CR",
	"QA",
	"SV",
	"HN",
	"NI",
	"PY",
	"UY",
	"PR",
	"BA",
	"PS",
	"TN",
	"BH",
	"VN",
	"GH",
	"MU",
	"UA",
	"MT",
	"BS",
	"MV",
	"OM",
	"MK",
	"LV",
	"EE",
	"IQ",
	"DZ",
	"AL",
	"NP",
	"MO",
	"ME",
	"SN",
	"GE",
	"BN",
	"UG",
	"GP",
	"BB",
	"AZ",
	"TZ",
	"LY",
	"MQ",
	"CM",
	"BW",
	"ET",
	"KZ",
	"NA",
	"MG",
	"NC",
	"MD",
	"FJ",
	"BY",
	"JE",
	"GU",
	"YE",
	"ZM",
	"IM",
	"HT",
	"KH",
	"AW",
	"PF",
	"AF",
	"BM",
	"GY",
	"AM",
	"MW",
	"AG",
	"RW",
	"GG",
	"GM",
	"FO",
	"LC",
	"KY",
	"BJ",
	"AD",
	"GD",
	"VI",
	"BZ",
	"VC",
	"MN",
	"MZ",
	"ML",
	"AO",
	"GF",
	"UZ",
	"DJ",
	"BF",
	"MC",
	"TG",
	"GL",
	"GA",
	"GI",
	"CD",
	"KG",
	"PG",
	"BT",
	"KN",
	"SZ",
	"LS",
	"LA",
	"LI",
	"MP",
	"SR",
	"SC",
	"VG",
	"TC",
	"DM",
	"MR",
	"AX",
	"SM",
	"SL",
	"NE",
	"CG",
	"AI",
	"YT",
	"CV",
	"GN",
	"TM",
	"BI",
	"TJ",
	"VU",
	"SB",
	"ER",
	"WS",
	"AS",
	"FK",
	"GQ",
	"TO",
	"KM",
	"PW",
	"FM",
	"CF",
	"SO",
	"MH",
	"VA",
	"TD",
	"KI",
	"ST",
	"TV",
	"NR",
	"RE",
	"LR",
	"ZW",
	"CI",
	"MM",
	"AN",
	"AQ",
	"BQ",
	"BV",
	"IO",
	"CX",
	"CC",
	"CK",
	"CW",
	"TF",
	"GW",
	"HM",
	"XK",
	"MS",
	"NU",
	"NF",
	"PN",
	"BL",
	"SH",
	"MF",
	"PM",
	"SX",
	"GS",
	"SS",
	"SJ",
	"TL",
	"TK",
	"UM",
	"WF",
	"EH",
	"SY",
);

const AdType = S.Literal(
	"ALL",
	"EMPLOYMENT_ADS",
	"FINANCIAL_PRODUCTS_AND_SERVICES_ADS",
	"HOUSING_ADS",
	"POLITICAL_AND_ISSUE_ADS",
);

const MediaType = S.Literal("ALL", "IMAGE", "MEME", "VIDEO", "NONE");

const PublisherPlatform = S.Literal(
	"FACEBOOK",
	"INSTAGRAM",
	"AUDIENCE_NETWORK",
	"MESSENGER",
	"WHATSAPP",
	"OCULUS",
	"THREADS",
);

const SearchType = S.Literal("KEYWORD_UNORDERED", "KEYWORD_EXACT_PHRASE");

const TargetGender = S.Literal("Women", "Men", "All");

const EstimatedAudienceSizeBoundary = S.Literal(
	100,
	1000,
	5000,
	10000,
	50000,
	100000,
	500000,
	1000000,
);

// Supporting schemas
const InsightsRangeValue = S.Struct({
	lower_bound: S.optional(S.Number),
	upper_bound: S.optional(S.Number),
});

const AudienceDistribution = S.Struct({
	percentage: S.optional(S.Number),
	age: S.optional(S.String),
	gender: S.optional(S.String),
	region: S.optional(S.String),
});

const AgeCountryGenderReachBreakdown = S.Struct({
	age_range: S.optional(S.String),
	country: S.optional(S.String),
	gender: S.optional(S.String),
	reach: S.optional(S.Number),
});

const BeneficiaryPayer = S.Struct({
	beneficiary: S.optional(S.String),
	payer: S.optional(S.String),
});

const TargetLocation = S.Struct({
	type: S.optional(S.Literal("included", "excluded")),
	name: S.optional(S.String),
	location_type: S.optional(S.String),
});

const KeyValue = S.Struct({
	key: S.String,
	value: S.Number,
});

// Search Parameters Schema
export const AdLibrarySearchParams = S.Struct({
	ad_active_status: S.optional(AdActiveStatus),
	ad_delivery_date_max: S.optional(S.String), // YYYY-MM-DD format
	ad_delivery_date_min: S.optional(S.String), // YYYY-MM-DD format
	ad_reached_countries: S.Array(Country), // Required
	ad_type: S.optional(AdType),
	bylines: S.optional(S.Array(S.String)), // Only for POLITICAL_AND_ISSUE_ADS
	delivery_by_region: S.optional(S.Array(S.String)), // Only for POLITICAL_AND_ISSUE_ADS
	estimated_audience_size_max: S.optional(EstimatedAudienceSizeBoundary),
	estimated_audience_size_min: S.optional(EstimatedAudienceSizeBoundary),
	languages: S.optional(S.Array(S.String)), // ISO 639-1/639-3 codes
	media_type: S.optional(MediaType),
	publisher_platforms: S.optional(S.Array(PublisherPlatform)),
	search_page_ids: S.optional(S.Array(S.Number)), // Max 10 IDs
	search_terms: S.optional(S.String), // Max 100 characters
	search_type: S.optional(SearchType),
	unmask_removed_content: S.optional(S.Boolean),
});

// Ad Response Schema
export const AdLibraryAd = S.Struct({
	id: S.String,
	ad_creation_time: S.optional(S.String),
	ad_creative_bodies: S.optional(S.Array(S.String)),
	ad_creative_link_captions: S.optional(S.Array(S.String)),
	ad_creative_link_descriptions: S.optional(S.Array(S.String)),
	ad_creative_link_titles: S.optional(S.Array(S.String)),
	ad_delivery_start_time: S.optional(S.String),
	ad_delivery_stop_time: S.optional(S.String),
	ad_snapshot_url: S.optional(S.String),
	age_country_gender_reach_breakdown: S.optional(
		S.Array(AgeCountryGenderReachBreakdown),
	),
	beneficiary_payers: S.optional(S.Array(BeneficiaryPayer)),
	br_total_reach: S.optional(S.Number),
	bylines: S.optional(S.String),
	currency: S.optional(S.String),
	delivery_by_region: S.optional(S.Array(AudienceDistribution)),
	demographic_distribution: S.optional(S.Array(AudienceDistribution)),
	estimated_audience_size: S.optional(InsightsRangeValue),
	eu_total_reach: S.optional(S.Number),
	impressions: S.optional(InsightsRangeValue),
	languages: S.optional(S.Array(S.String)),
	page_id: S.optional(S.String),
	page_name: S.optional(S.String),
	publisher_platforms: S.optional(S.Array(PublisherPlatform)),
	spend: S.optional(InsightsRangeValue),
	target_ages: S.optional(S.Array(S.String)),
	target_gender: S.optional(TargetGender),
	target_locations: S.optional(S.Array(TargetLocation)),
	total_reach_by_location: S.optional(S.Array(KeyValue)),
});

// Response wrapper (typical API response structure)
export const AdLibraryResponse = S.Struct({
	data: S.Array(AdLibraryAd),
	paging: S.optional(
		S.Struct({
			cursors: S.optional(
				S.Struct({
					before: S.optional(S.String),
					after: S.optional(S.String),
				}),
			),
			next: S.optional(S.String),
			previous: S.optional(S.String),
		}),
	),
});

// Type exports
export type AdLibrarySearchParams = S.Schema.Type<typeof AdLibrarySearchParams>;
export type AdLibraryAd = S.Schema.Type<typeof AdLibraryAd>;
export type AdLibraryResponse = S.Schema.Type<typeof AdLibraryResponse>;
